apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000  # optional, or let Kubernetes assign
